### ISSUE TITLE
Bugs with text in bash/gnome terminal

### ISSUE THREAD

**Issue by silentpatrik** [bakks/butterfish#21]
Soon 6 in the morning and at least a 24h session :boom:  lets hope I missed something and no bug.

I have tested with bash "vanilla" and with "oh my bash"using default terminal app both as normal user and elevated and same behaviour on a pretty fresh popos (ubuntu 22). Maybe my terminal settings but i reset them to default to make sure, env TERM=xterm-256color with unicode.
Anyway, a few glitches when using mainly home/end keys but from time to time arrow keys and especially when jumping words with ctrl. If its my settings, dont feel ashamed to close this ticket :smile: 

Great tool btw, really useful with or without these minor issues. 

Thank you and good night. 

![bug](https://github.com/bakks/butterfish/assets/77385235/07f11a6c-9333-4f2c-b534-b04d4e9bef97)

**Comment by bakks** [comment]
Thanks for adding this bug report! Yep i think there are several issues
here:
- The issue in the gif I haven’t seen, but I will take a look and try to
replicate
- The bugs with arrow keys I was aware of but haven’t yet had time to fix,
basically I need to figure out a way to edit butterfish’s buffered version
of the shell command when arrows are pressed.
- home/end I hadn’t thought about, those keys just go to the start and end
of the line
- word hopping I hadn’t thought about! A less common feature

So these are definitely bugs, basically Butterfish intercepts shell text
input/output and keeps a buffer of what the command is — these are
edge-cases not yet covered but should be covered. I’ll follow up with fixes.

**Comment by bakks** [comment]
@silentpatrik I've pushed 2e5b3041abd32176114f4416691202aaebe57919 in an attempt to fix this, it is now on the main branch. I'm not certain that I've fully fixed this but please try the updated version. Haven't yet pushed a release with this.

**Comment by silentpatrik** [comment]
Yea,this works very good. I did manage to force a few glitches but it was when using oh-my-bash and from an ssh session and is probably not something you want to focus on. Since it works if i run a clean bash session and dont abuse the shell to much like sending to background or press "ctrl-c", but its unrelated to original issue so i create a new issue if it becomes an issue or if you ask me to. When exiting the bf shell using ctrl-d works perfect however so its trivial.

**Comment by silentpatrik** [comment]
can i close this?

**Comment by bakks** [comment]
Yep feel free to close this, glad it was resolved for you. And please create other tickets as you come across issues! I'm trying to plug these holes so it's very helpful if you surface them.
