### ISSUE TITLE
Better examples in the README here on github

### ISSUE THREAD

**Issue by emilBeBri** [bakks/butterfish#4]
I'm a reasonably profficient user of the shell, and the man page with listing of the flags are good. However, some concrete examples of the following would be nice, at least to me, and I'm probably not the only one I would think:

- How to get butterfish to use previous instructions and answers? I  would think the answer would be using the shell mode. 
- the yaml idea is neat, but how do you use it? For some, this might be obvious. It isn't for me, and I'm not a newbie.
- examples of how to use the index to generate responses based on local text. This is really exciting, and although it does seems possible to infer how to it  from the readme, I think an example could spell it out in a very nice way that would highlight this extremely useful feature.  

Hope you find the input useful, let me know how I can assist you.

**Comment by bakks** [comment]
Hey @emilBeBri - this is great feedback, I will add details to the help here in the next few days. I think it's a good goal that you can understand the Butterfish from only the binary, rather than requiring referencing the readme.

**Comment by bakks** [comment]
Also to answer your first question:
> How to get butterfish to use previous instructions and answers? I would think the answer would be using the shell mode.

Yes, shell mode is the right way to do this. Part of the basic functionality is to manage a history for you, so previous command output AND previous prompt input/output is visible.

**Comment by bakks** [comment]
Added detail in b26e0aa8239f29f7e2c399e415f6a71a84a013b1

@emilBeBri Please take a look and let me know if that's helpful. Very curious if that clarifies the use-cases or if you have more questions, let me know!
